"""add image message

Revision ID: b4568a93b49a
Revises: 600fa02c0e91
Create Date: 2026-09-29 18:20:44.541996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4568a93b49a'
down_revision: Union[str, Sequence[str], None] = '600fa02c0e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('image_key', sa.String(length=500), nullable=True))
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'content',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('message', 'image_key')
    # ### end Alembic commands ###
